// <auto-generated />
using System;
using Hospital_Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Website.Migrations
{
    [DbContext(typeof(Hospital_WebsiteContext))]
    [Migration("20240101182226_r")]
    partial class r
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hospital_Website.Models.doktor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("poliklinikid")
                        .HasColumnType("int");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("poliklinikid");

                    b.ToTable("doktor");
                });

            modelBuilder.Entity("Hospital_Website.Models.hasta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("hasta");
                });

            modelBuilder.Entity("Hospital_Website.Models.hastane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ilceID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ilceID");

                    b.ToTable("hastane");
                });

            modelBuilder.Entity("Hospital_Website.Models.il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("il");
                });

            modelBuilder.Entity("Hospital_Website.Models.ilce", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("ilID")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("ilID");

                    b.ToTable("ilce");
                });

            modelBuilder.Entity("Hospital_Website.Models.poliklinik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hastaneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("hastaneId");

                    b.ToTable("poliklinik");
                });

            modelBuilder.Entity("Hospital_Website.Models.randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doktorID")
                        .HasColumnType("int");

                    b.Property<int>("hastaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("doktorID");

                    b.HasIndex("hastaID");

                    b.ToTable("randevu");
                });

            modelBuilder.Entity("Hospital_Website.Models.doktor", b =>
                {
                    b.HasOne("Hospital_Website.Models.poliklinik", "poliklinik")
                        .WithMany("Doktorlar")
                        .HasForeignKey("poliklinikid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("poliklinik");
                });

            modelBuilder.Entity("Hospital_Website.Models.hastane", b =>
                {
                    b.HasOne("Hospital_Website.Models.ilce", "ilce")
                        .WithMany("hastaneler")
                        .HasForeignKey("ilceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ilce");
                });

            modelBuilder.Entity("Hospital_Website.Models.ilce", b =>
                {
                    b.HasOne("Hospital_Website.Models.il", "il")
                        .WithMany("ilceler")
                        .HasForeignKey("ilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("il");
                });

            modelBuilder.Entity("Hospital_Website.Models.poliklinik", b =>
                {
                    b.HasOne("Hospital_Website.Models.hastane", "hastane")
                        .WithMany("poliklinikler")
                        .HasForeignKey("hastaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hastane");
                });

            modelBuilder.Entity("Hospital_Website.Models.randevu", b =>
                {
                    b.HasOne("Hospital_Website.Models.doktor", "doktor")
                        .WithMany()
                        .HasForeignKey("doktorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Website.Models.hasta", "hasta")
                        .WithMany("randevular")
                        .HasForeignKey("hastaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doktor");

                    b.Navigation("hasta");
                });

            modelBuilder.Entity("Hospital_Website.Models.hasta", b =>
                {
                    b.Navigation("randevular");
                });

            modelBuilder.Entity("Hospital_Website.Models.hastane", b =>
                {
                    b.Navigation("poliklinikler");
                });

            modelBuilder.Entity("Hospital_Website.Models.il", b =>
                {
                    b.Navigation("ilceler");
                });

            modelBuilder.Entity("Hospital_Website.Models.ilce", b =>
                {
                    b.Navigation("hastaneler");
                });

            modelBuilder.Entity("Hospital_Website.Models.poliklinik", b =>
                {
                    b.Navigation("Doktorlar");
                });
#pragma warning restore 612, 618
        }
    }
}
